name: habit_tracker_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0" # Verifique se esta versão é compatível com o seu Flutter

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^19.2.1 # Versão específica
  timezone: ^0.10.1 # Versão específica
  flutter_native_timezone: ^2.0.0
  intl: ^0.18.1 # Adicionado para formatação de data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Use a versão mais recente se quiser linting mais rigoroso

flutter:
  uses-material-design: true

  # Para o ícone de notificação do Android
  assets:
    # - android/app/src/main/res/drawable/app_icon_notification.png # Certifique-se de ter este arquivo
